

batch_size: 24
iters: 140

data_root: /kaggle/input/

train_dataset:
  type: Abdomen
  dataset_root: /kaggle/working/data
  result_dir: /kaggle/working/data/results
  transforms:
    - type: RandomFlip3D
      flip_axis: [1, 2]
    - type: RandomQuarterTurn3D
      rotate_planes: [[ 1, 2 ]]
    - type: RandomRotation3D
      degrees: 20
      rotate_planes: [[1, 2]]
    - type: Resize3D
      size: [1, 224, 224]
  mode: train
  num_classes: 2

val_dataset:
  type: Abdomen
  dataset_root: /kaggle/working/data
  result_dir: /kaggle/working/data/results
  num_classes: 2
  transforms:
    - type: Resize3D
      size: [1, 224, 224]
  mode: val
  dataset_json_path: Null

test_dataset:
  type: Abdomen
  dataset_root: /kaggle/working/data
  result_dir: /kaggle/working/data/results
  num_classes: 2
  transforms:
    - type: Resize3D
      size: [1, 224, 224]
  mode: val
  dataset_json_path: Null

model:
  type: SwinUNet
  backbone:
    type: SwinTransformer_tinier_patch4_window7_224
  num_classes: 2
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.05
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: DiceLoss
      coef: [0.4, 0.6]
  coef: [1]

export:
  transforms:
    - type: Resize3D
      size: [ 1 ,224, 224 ]
  inference_helper:
    type: InferenceHelper2D
    
    
